"""
Simarine protocol client and parser.

Provides transport, protocol decoding, and object models for devices and sensors.
"""

from .client import SimarineClient
from .exceptions import (
  ProtocolError,
  InvalidHeaderLength,
  InvalidHeaderPreamble,
  InvalidHeaderMarker,
  MessageTypeMismatch,
  InvalidMessageLength,
  InvalidChecksumMarker,
  CRCMismatch,
  TransportError,
  TransportOpenError,
  TransportAlreadyOpen,
  ClientError,
  UDPListenerAlreadyRunning,
  UDPListenerNotRunning,
)
from .protocol import MessageType, MessageFieldType, MessageFields
from .transport import DEFAULT_TCP_PORT, DEFAULT_UDP_PORT
from .types import (
  Device,
  NullDevice,
  VoltmeterDevice,
  AmperemeterDevice,
  ThermometerDevice,
  BarometerDevice,
  OhmmeterDevice,
  TimeDevice,
  TankDevice,
  BatteryDevice,
  SystemDevice,
  InclinometerDevice,
  Sensor,
  NoneSensor,
  VoltageSensor,
  CurrentSensor,
  CoulombCounterSensor,
  TemperatureSensor,
  AtmosphereSensor,
  AtmosphereTrendSensor,
  ResistanceSensor,
  TimestampSensor,
  AngleSensor,
  UserSensor,
  OnOffType,
  BatteryType,
  InclinometerType,
  InclinometerDisplayType,
  TankFluidType,
  ThermometerType,
  TimestampStateType,
)

__all__: tuple[str, ...] = [
  "SimarineClient",
  "ProtocolError",
  "InvalidHeaderLength",
  "InvalidHeaderPreamble",
  "InvalidHeaderMarker",
  "MessageTypeMismatch",
  "InvalidMessageLength",
  "InvalidChecksumMarker",
  "CRCMismatch",
  "TransportError",
  "TransportOpenError",
  "TransportAlreadyOpen",
  "ClientError",
  "UDPListenerAlreadyRunning",
  "UDPListenerNotRunning",
  "MessageType",
  "MessageFieldType",
  "MessageFields",
  "DEFAULT_TCP_PORT",
  "DEFAULT_UDP_PORT",
  "Device",
  "NullDevice",
  "VoltmeterDevice",
  "AmperemeterDevice",
  "ThermometerDevice",
  "BarometerDevice",
  "OhmmeterDevice",
  "TimeDevice",
  "TankDevice",
  "BatteryDevice",
  "SystemDevice",
  "InclinometerDevice",
  "Sensor",
  "NoneSensor",
  "VoltageSensor",
  "CurrentSensor",
  "CoulombCounterSensor",
  "TemperatureSensor",
  "AtmosphereSensor",
  "AtmosphereTrendSensor",
  "ResistanceSensor",
  "TimestampSensor",
  "AngleSensor",
  "UserSensor",
  "OnOffType",
  "BatteryType",
  "InclinometerType",
  "InclinometerDisplayType",
  "TankFluidType",
  "ThermometerType",
  "TimestampStateType",
]
