"""
Simarine protocol client and parser.

Provides transport, protocol decoding, and object models for devices and sensors.
"""

from .client import SimarineClient, SimarineMQTTClient, SimarineUDPClient
from .exceptions import (
  ProtocolError,
  InvalidHeaderLength,
  InvalidHeaderPreamble,
  InvalidHeaderMarker,
  MessageTypeMismatch,
  InvalidMessageLength,
  InvalidChecksumMarker,
  CRCMismatch,
  TransportError,
  TransportOpenError,
  TransportAlreadyOpen,
  ClientError,
  UDPListenerAlreadyRunning,
  UDPListenerNotRunning,
)
from .protocol import MessageType, MessageFieldType, MessageFields
from .transport import DEFAULT_TCP_PORT, DEFAULT_UDP_PORT, DEFAULT_MQTT_HOST, DEFAULT_MQTT_PORT
from .types import (
  Device,
  NoneDevice,
  VoltmeterDevice,
  AmperemeterDevice,
  ThermometerDevice,
  BarometerDevice,
  OhmmeterDevice,
  TimeDevice,
  TankDevice,
  BatteryDevice,
  SystemDevice,
  InclinometerDevice,
  Sensor,
  NoneSensor,
  VoltageSensor,
  CurrentSensor,
  CoulombCounterSensor,
  TemperatureSensor,
  AtmosphereSensor,
  AtmosphereTrendSensor,
  ResistanceSensor,
  TimestampSensor,
  AngleSensor,
  UserSensor,
  OnOffType,
  BatteryType,
  InclinometerType,
  InclinometerDisplayType,
  TankFluidType,
  ThermometerType,
  TimestampStateType,
  StateOfChargeSensor,
  RemainingTimeSensor,
)

__all__: tuple[str, ...] = [
  # client
  "SimarineClient",
  "SimarineMQTTClient",
  "SimarineUDPClient",
  # exceptions
  "ProtocolError",
  "InvalidHeaderLength",
  "InvalidHeaderPreamble",
  "InvalidHeaderMarker",
  "MessageTypeMismatch",
  "InvalidMessageLength",
  "InvalidChecksumMarker",
  "CRCMismatch",
  "TransportError",
  "TransportOpenError",
  "TransportAlreadyOpen",
  "ClientError",
  "UDPListenerAlreadyRunning",
  "UDPListenerNotRunning",
  # protocol
  "MessageType",
  "MessageFieldType",
  "MessageFields",
  # transport
  "DEFAULT_TCP_PORT",
  "DEFAULT_UDP_PORT",
  "DEFAULT_MQTT_HOST",
  "DEFAULT_MQTT_PORT",
  # types
  "Device",
  "NoneDevice",
  "VoltmeterDevice",
  "AmperemeterDevice",
  "ThermometerDevice",
  "BarometerDevice",
  "OhmmeterDevice",
  "TimeDevice",
  "TankDevice",
  "BatteryDevice",
  "SystemDevice",
  "InclinometerDevice",
  "Sensor",
  "NoneSensor",
  "VoltageSensor",
  "CurrentSensor",
  "CoulombCounterSensor",
  "TemperatureSensor",
  "AtmosphereSensor",
  "AtmosphereTrendSensor",
  "ResistanceSensor",
  "TimestampSensor",
  "AngleSensor",
  "UserSensor",
  "OnOffType",
  "BatteryType",
  "InclinometerType",
  "InclinometerDisplayType",
  "TankFluidType",
  "ThermometerType",
  "TimestampStateType",
  "StateOfChargeSensor",
  "RemainingTimeSensor",
]
